import React from 'react';

const AnalysisResults = ({ result, onReset }) => {
  const { analysis, features, transcription, recommendations } = result;

  const getProbabilityColor = (probability) => {
    if (probability < 0.3) return { bg: 'bg-success-500', text: 'text-success-700', bgLight: 'bg-success-50' };
    if (probability < 0.7) return { bg: 'bg-warning-500', text: 'text-warning-700', bgLight: 'bg-warning-50' };
    return { bg: 'bg-danger-500', text: 'text-danger-700', bgLight: 'bg-danger-50' };
  };

  const getConfidenceColor = (confidence) => {
    switch (confidence.toLowerCase()) {
      case 'high': return 'text-success-600';
      case 'medium': return 'text-warning-600';
      case 'low': return 'text-danger-600';
      default: return 'text-neutral-600';
    }
  };

  const probabilityColors = getProbabilityColor(analysis.probability);

  const downloadReport = () => {
    const date = new Date().toLocaleString();
    const reportContent = `
ADHD SPEECH ANALYSIS REPORT
Generated on: ${date}

═══════════════════════════════════════════════════════════

ANALYSIS SUMMARY
═══════════════════════════════════════════════════════════

Classification: ${analysis.classification}
ADHD Probability: ${(analysis.probability * 100).toFixed(1)}%
Confidence Level: ${analysis.confidence}

${analysis.probability < 0.3 ? 'Status: Low Risk' : 
  analysis.probability < 0.7 ? 'Status: Medium Risk' : 'Status: High Risk'}

═══════════════════════════════════════════════════════════

ACOUSTIC FEATURES
═══════════════════════════════════════════════════════════

Pitch (Mean): ${features.pitch_mean.toFixed(2)} Hz
  Description: Fundamental frequency of the voice

Jitter: ${features.jitter.toFixed(4)}
  Description: Voice stability measurement

Shimmer: ${features.shimmer.toFixed(4)}
  Description: Amplitude variation in voice

═══════════════════════════════════════════════════════════

LINGUISTIC FEATURES
═══════════════════════════════════════════════════════════

Lexical Diversity: ${(features.lexical_diversity * 100).toFixed(1)}%
  Description: Vocabulary richness indicator

Coherence Score: ${(features.coherence * 100).toFixed(1)}%
  Description: Story structure quality

Filler Words: ${features.fillers}
  Description: Use of "um", "uh", and similar words

${transcription && analysis.transcription_available ? `
═══════════════════════════════════════════════════════════

SPEECH TRANSCRIPTION
═══════════════════════════════════════════════════════════

${transcription}

Note: Transcription may not be 100% accurate and is provided for reference only.
` : ''}

${recommendations ? `
═══════════════════════════════════════════════════════════

RECOMMENDATIONS
═══════════════════════════════════════════════════════════

${recommendations.warning || recommendations.message}

${recommendations.note ? `\n${recommendations.note}` : ''}
${recommendations.advice ? `\n${recommendations.advice}` : ''}
` : ''}

═══════════════════════════════════════════════════════════

IMPORTANT MEDICAL DISCLAIMER
═══════════════════════════════════════════════════════════

This tool is for screening purposes only and should not replace 
professional medical diagnosis. Results should be interpreted by 
qualified healthcare professionals. Early intervention can 
significantly improve outcomes.

═══════════════════════════════════════════════════════════

Report generated by ADHD Speech Detection System
For questions or concerns, please consult with a healthcare professional.

`;

    // Create a blob with the report content
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    // Create a temporary anchor element and trigger download
    const link = document.createElement('a');
    link.href = url;
    link.download = `ADHD_Analysis_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    
    // Clean up
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-12 animate-fade-in-up">
      {/* Header */}
      <div className="text-center">
        <h2 className="text-4xl lg:text-5xl font-bold text-neutral-900 mb-4">
          Analysis Complete
        </h2>
        <p className="text-xl text-neutral-600">
          Here are your comprehensive speech analysis results
        </p>
      </div>

      {/* Main Probability Display */}
      <div className="bg-white rounded-3xl shadow-large p-8 lg:p-12 text-center card-hover">
        <div className={`inline-flex items-center justify-center w-32 h-32 rounded-full ${probabilityColors.bg} mb-8`}>
          <div className="text-center text-white">
            <div className="text-3xl font-black">
              {(analysis.probability * 100).toFixed(0)}%
            </div>
            <div className="text-sm font-medium">ADHD Probability</div>
          </div>
        </div>

        <h3 className="text-2xl font-bold text-neutral-900 mb-4">
          {analysis.classification}
        </h3>

        <div className={`inline-flex items-center px-6 py-3 rounded-full text-sm font-semibold ${probabilityColors.bgLight} ${probabilityColors.text} mb-6`}>
          <span className={`inline-block w-2 h-2 rounded-full mr-2 ${
            analysis.probability < 0.3 ? 'bg-success-500' :
            analysis.probability < 0.7 ? 'bg-warning-500' : 'bg-danger-500'
          }`}></span>
          {analysis.confidence} Confidence
        </div>

        {/* Progress Bar */}
        <div className="max-w-md mx-auto mb-8">
          <div className="w-full bg-neutral-200 rounded-full h-3">
            <div
              className={`h-3 rounded-full transition-all duration-1000 ${probabilityColors.bg}`}
              style={{ width: `${analysis.probability * 100}%` }}
            ></div>
          </div>
          <div className="flex justify-between text-sm text-neutral-500 mt-2">
            <span>Low Risk</span>
            <span>High Risk</span>
          </div>
        </div>
      </div>

      {/* Recommendations */}
      {recommendations && (
        <div className={`rounded-3xl p-8 lg:p-12 ${
          analysis.probability > 0.5
            ? 'bg-danger-50 border border-danger-200'
            : 'bg-success-50 border border-success-200'
        }`}>
          <div className="flex items-start">
            <div className="flex-shrink-0 mr-6">
              {analysis.probability > 0.5 ? (
                <div className="w-16 h-16 bg-danger-100 rounded-2xl flex items-center justify-center">
                  <svg className="w-8 h-8 text-danger-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
                  </svg>
                </div>
              ) : (
                <div className="w-16 h-16 bg-success-100 rounded-2xl flex items-center justify-center">
                  <svg className="w-8 h-8 text-success-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
              )}
            </div>
            <div className="flex-1">
              <h3 className={`text-2xl font-bold mb-4 ${
                analysis.probability > 0.5 ? 'text-danger-900' : 'text-success-900'
              }`}>
                {recommendations.warning || recommendations.message}
              </h3>
              {recommendations.note && (
                <p className="text-lg text-neutral-700 mb-4 leading-relaxed">{recommendations.note}</p>
              )}
              {recommendations.advice && (
                <p className="text-lg font-semibold text-neutral-900">{recommendations.advice}</p>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Detailed Analysis Grid */}
      <div className="grid lg:grid-cols-2 gap-8">
        {/* Acoustic Features */}
        <div className="bg-white rounded-3xl shadow-large p-8 card-hover">
          <div className="flex items-center mb-8">
            <div className="w-12 h-12 bg-blue-100 rounded-2xl flex items-center justify-center mr-4">
              <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
              </svg>
            </div>
            <h3 className="text-2xl font-bold text-neutral-900">Acoustic Features</h3>
          </div>

          <div className="space-y-6">
            <div className="flex justify-between items-center py-4 border-b border-neutral-100">
              <div>
                <div className="font-semibold text-neutral-900">Pitch (Mean)</div>
                <div className="text-sm text-neutral-500">Fundamental frequency</div>
              </div>
              <div className="text-right">
                <div className="text-xl font-bold text-neutral-900">{features.pitch_mean.toFixed(2)} Hz</div>
              </div>
            </div>

            <div className="flex justify-between items-center py-4 border-b border-neutral-100">
              <div>
                <div className="font-semibold text-neutral-900">Jitter</div>
                <div className="text-sm text-neutral-500">Voice stability</div>
              </div>
              <div className="text-right">
                <div className="text-xl font-bold text-neutral-900">{features.jitter.toFixed(4)}</div>
              </div>
            </div>

            <div className="flex justify-between items-center py-4">
              <div>
                <div className="font-semibold text-neutral-900">Shimmer</div>
                <div className="text-sm text-neutral-500">Amplitude variation</div>
              </div>
              <div className="text-right">
                <div className="text-xl font-bold text-neutral-900">{features.shimmer.toFixed(4)}</div>
              </div>
            </div>
          </div>
        </div>

        {/* Linguistic Features */}
        <div className="bg-white rounded-3xl shadow-large p-8 card-hover">
          <div className="flex items-center mb-8">
            <div className="w-12 h-12 bg-green-100 rounded-2xl flex items-center justify-center mr-4">
              <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
              </svg>
            </div>
            <h3 className="text-2xl font-bold text-neutral-900">Linguistic Features</h3>
          </div>

          <div className="space-y-6">
            <div className="flex justify-between items-center py-4 border-b border-neutral-100">
              <div>
                <div className="font-semibold text-neutral-900">Lexical Diversity</div>
                <div className="text-sm text-neutral-500">Vocabulary richness</div>
              </div>
              <div className="text-right">
                <div className="text-xl font-bold text-neutral-900">{(features.lexical_diversity * 100).toFixed(1)}%</div>
              </div>
            </div>

            <div className="flex justify-between items-center py-4 border-b border-neutral-100">
              <div>
                <div className="font-semibold text-neutral-900">Coherence Score</div>
                <div className="text-sm text-neutral-500">Story structure quality</div>
              </div>
              <div className="text-right">
                <div className="text-xl font-bold text-neutral-900">{(features.coherence * 100).toFixed(1)}%</div>
              </div>
            </div>

            <div className="flex justify-between items-center py-4">
              <div>
                <div className="font-semibold text-neutral-900">Filler Words</div>
                <div className="text-sm text-neutral-500">Use of "um", "uh", etc.</div>
              </div>
              <div className="text-right">
                <div className="text-xl font-bold text-neutral-900">{features.fillers}</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Transcription */}
      {transcription && analysis.transcription_available && (
        <div className="bg-white rounded-3xl shadow-large p-8 lg:p-12 card-hover">
          <div className="flex items-center mb-8">
            <div className="w-12 h-12 bg-purple-100 rounded-2xl flex items-center justify-center mr-4">
              <svg className="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
              </svg>
            </div>
            <h3 className="text-2xl font-bold text-neutral-900">Speech Transcription</h3>
          </div>

          <div className="bg-neutral-50 rounded-2xl p-8">
            <p className="text-lg text-neutral-800 leading-relaxed whitespace-pre-wrap font-medium">
              {transcription}
            </p>
          </div>

          <p className="text-sm text-neutral-500 mt-6 text-center">
            * Transcription may not be 100% accurate and is provided for reference only
          </p>
        </div>
      )}

      {/* Actions */}
      <div className="text-center">
        <button
          onClick={() => {
            console.log('Reset button clicked');
            if (onReset) {
              onReset();
            } else {
              console.error('onReset function not provided');
            }
          }}
          className="btn-secondary mr-4"
        >
          Analyze Another File
        </button>
        <button
          onClick={downloadReport}
          className="btn-primary"
        >
          Download Report
        </button>
      </div>

      {/* Disclaimer */}
      <div className="bg-yellow-50 border border-yellow-200 rounded-3xl p-8">
        <div className="flex items-start">
          <div className="flex-shrink-0 mr-6">
            <div className="w-12 h-12 bg-yellow-100 rounded-2xl flex items-center justify-center">
              <svg className="w-6 h-6 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
              </svg>
            </div>
          </div>
          <div className="flex-1">
            <h3 className="text-xl font-bold text-yellow-900 mb-4">Important Medical Disclaimer</h3>
            <p className="text-yellow-800 leading-relaxed">
              This tool is for screening purposes only and should not replace professional medical diagnosis.
              Results should be interpreted by qualified healthcare professionals. Early intervention can significantly improve outcomes.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalysisResults;